name: C++ CI with Advanced Caching

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            triplet: x64-linux
            enable_coverage: true
            os_name: Linux
            compiler: gcc-11
          - os: windows-latest
            triplet: x64-windows
            enable_coverage: false
            os_name: Windows
            compiler: msvc-2022

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup comprehensive caching
        uses: ./.github/actions/setup-cache
        with:
          os: ${{ matrix.os_name }}
          triplet: ${{ matrix.triplet }}
          compiler: ${{ matrix.compiler }}

      - name: Setup build environment
        uses: ./.github/actions/setup-build-env
        with:
          os: ${{ matrix.os_name }}

      - name: Setup vcpkg
        uses: ./.github/actions/setup-vcpkg
        with:
          triplet: ${{ matrix.triplet }}
          os: ${{ matrix.os_name }}

      - name: Build and test
        uses: ./.github/actions/build-and-test
        with:
          enable_coverage: ${{ matrix.enable_coverage }}
          os: ${{ matrix.os_name }}

      - name: Upload coverage report
        if: matrix.enable_coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/coverage_report

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          path: build/Testing/